export default {
  BRAND_GET_BRAND_PROFILE: "BRAND_GET_BRAND_PROFILE",
  BRAND_TOGGLE_LOADING: "BRAND_TOGGLE_LOADING",
  FOLLOW_BRAND: "FOLLOW_BRAND",
  GET_BRAND_PROFILE: "GET_BRAND_PROFILE",
  BRAND_PROFILE_TOGGLE_TABS: "BRAND_PROFILE_TOGGLE_TABS",
  BRAND_GET_ALL_FOLLOWERS: "BRAND_GET_ALL_FOLLOWERS"
};
